### ISSUE TITLE
Extract store from seneca's core

### ISSUE THREAD

**Issue by esnunes** [rjrodger/seneca#138]
Hi,

I'm considering using seneca to develop microservices, at the moment I use REST over HTTP to communicate between them. Seneca's transport layer is really interesting, the ability to run it over HTTP, TCP, AMQP, etc is awesome. There is just one point that is not clear enough for me, the stores / model.

Shouldn't the stores/model part of seneca be an external project? Something like a plugin? I know that the idea of seneca is to be much more than a transport layer, I'm ok with it but in case shouldn't the store/model part be a total external plugin?

I'm sorry if I got totally wrong the idea of seneca.

**Comment by rjrodger** [comment]
production stores are indeed separate plugins - see all the seneca-*-store plugins

however the seneca entity API provides a convenience API, and this needs to be part of the main seneca API, otherwise it's not very convenient! :)
also, npm install seneca, with no additional plugins, should give you a basic system that provides in-memory storage - this is very useful for prototyping and unit tests
the entity API does not affect the message API, so can be safely ignored if you're not using it
